default:
    -git clone https://github.com/git-trainer-tasks/forget-about-that-1.git tasks/forget-about-that-1/src/repo
    docker build -f tasks/forget-about-that-1/src/Dockerfile -t git-trainer:forget-about-that-1 .
